src/Statics.ts

fix: add production account id

---

docs/Copy.md
src/Configuration.ts
src/StorageStack.ts

feat: remove ec2 instace

---

src/StorageStack.ts

fix: explicity enable serverside encryption using s3 key

---

src/StorageStack.ts
test/main.test.ts

feat: add list buckets permission and test for right count of buckets

---

src/StorageStack.ts

fix: allow all resrouces for listallmybuckets

---

src/StorageStack.ts
test/main.test.ts

- Bucket for aanbesteding
- User with rights to read from the bucket
- Credentials for the user can be created in the IAM console

feat: s3 bucket for aanbesteding (#18)

---

src/BackupStack.ts

fix: use temp role to allow access to bucket

---

src/utils.ts

fix: map to arns not bucket names

---

src/StorageStack.ts

feat: enable backup rule into deep archive

---

.projen/deps.json
.projenrc.js
package.json
src/BackupIamStack.ts
src/BackupStack.ts
src/Statics.ts
yarn.lock

feat: construct role arn by role name (for cross-account)

---

src/StorageStage.ts

fix: deploy IAM stack in target environment not in backup environment

---

docs/Backup.md
src/BackupStack.ts
src/Statics.ts
src/StorageStage.ts

- fix stack dependencies
- read and write for backup role on backup buckets

feat: grant read/write for backup role on backup buckets

---

docs/Backup.md
src/BackupStack.ts
src/Configuration.ts
src/Statics.ts
src/StorageStack.ts

- Setup KMS key for source buckets
- Setup permissions for using KMS key
- Remove non current object versions after 7 days

feat: move from sse-s3 to sse-kms to allow cross-account replication

---

src/BackupStack.ts

fix: allow changed ownership to destination

---

src/BackupStack.ts

fix: prermission should grant rights to account principal

---

src/StorageStack.ts

fix: sid statement constains spaces

---

src/StorageStack.ts

chore: allow to write to objects in buckets

---

src/Configuration.ts

fixa base path

---

src/CloudfrontStack.ts
src/Statics.ts
src/StorageStage.ts
src/UsEastStack.ts

feat: add certificate stuff

---

src/CloudfrontStack.ts

fix bucket iam

---

src/CloudfrontStack.ts

fix iam policy

---

src/CloudfrontStack.ts

fix build error

---

src/CloudfrontStack.ts
src/StorageStack.ts

fix kmskey access

---

src/CloudfrontStack.ts

iam KMS key

---

src/CloudfrontKmsPolicy.ts
src/CloudfrontStack.ts
src/StorageStack.ts

custom resource for kms key policy

---

src/CloudfrontStack.ts
src/S3BucketPolicyUpdater.ts

fix bucket policy creation

---

src/Configuration.ts

remove bucket

---

src/Configuration.ts
test/main.test.ts

enable bucket

---

src/Configuration.ts

enable another bucket

---

src/CloudfrontKmsPolicy.ts
src/CloudfrontStack.ts
src/S3BucketPolicyUpdater.ts
src/Statics.ts
src/WafStack.ts
test/main.test.ts

Feat/add Waf

---

src/StorageStage.ts

actually deploy the waf stack

---

.projen/deps.json
.projen/tasks.json
.projenrc.js
package.json
src/Configuration.ts
src/StorageStack.ts
yarn.lock

chore: code cleanup

---

docs/Backup.md

chore: empty commit to trigger the build

---

docs/Backup.md
docs/testurls.md
package.json
src/CloudfrontStack.ts
yarn.lock

fix: redirect without cloudfront function

---

src/CloudfrontStack.ts
tsconfig.dev.json
tsconfig.json

Fixes #600 #599 
removed unneeded exports to SSM Parameters

fix: change caching, add cache header, remove origin headers

---

src/Configuration.ts
src/StorageStack.ts
test/main.test.ts

- Configurable IAM users per environment
- Configurable IAM user access per bucket

feat: flexible IAM user access to geo buckets
